### ISSUE TITLE
Documents Card this.$refs.card is undefined and this.$refs.card.resize is not a function

### ISSUE THREAD

**Issue by stotes** [enso-ui/documents#4]
This is  a **bug**.

Documents Card watch->count method using card from $refs is undefined. 
If I include the ref, the resize method is non existent.
```vue
<template>
    <card collapsible
        ref="card"
```

```
Uncaught (in promise) TypeError: this.$refs.card is undefined
    count DocumentsCard.vue:101
```
```
Uncaught (in promise) TypeError: this.$refs.card.resize is not a function
    count DocumentsCard.vue:102
```

If I remove both references to the resize call the DocumentsCard component works fine.

**Comment by aocneanu** [comment]
Please open a new issue with step by step instructions on how to reproduce.
